version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs_bot
    container_name: nodejs_bot
    restart: unless-stopped
    env_file: .env
    ports:
      - "8081:8081"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/nodemon -x 'node index.js || (sleep 5; touch index.js)'

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
